Tõlkefunktsionaalsus sõnaanalüsaatorile
centre-for-educational-technology/evkk pull request #107
Opened 2022-08-29 01:18 UTC by harlikodasma

2022-09-25 11:21 UTC, mikktarvas requested changes

2022-09-25 11:21 UTC, mikktarvas commented on core/src/main/java/ee/tlu/evkk/core/service/maps/TranslationMappings.java
>  public class TranslationMappings {
Tõlkeid võiks hoida properties failides, springil täitsa tugi sellise asja jaoks olemas.

2022-09-30 07:18 UTC, harlikodasma commented on api/build.gradle
> +  // Lombok
Me ju kasutame JDK 11, kus recordite tuge veel pole? Tööl kasutame ka kõigis projektides Lombokit, isegi nendes, kus uusim Java versioon - teeb igatmoodi elu lihtsamaks. Või kuidas siin näite korral saaks ilma Lombokita lihtsasti getterid ja setterid paika, oskad mingi näite tuua? Ma saan praegu googeldades aru, et recordiga tuleks ka getterid/setterid ikkagi käsitsi teha ja et recordid ei ole mõeldud päris selle sugarina beanide asemele. Olen veidi segaduses selle koha pealt :D

2022-09-30 07:54 UTC, mikktarvas commented on api/build.gradle
> +  // Lombok
Varem või hiljem liigub platform uue LTS versiooni peale ja võtame recordid kasutusele. Recorditele ei ole vaja gettereid genereerida. Lombokist saab suure tõenäosusega lähiaastate jooksul legacy libra, mida siis peame hakkama jälle välja korjama. Praegu kõige otstarbekam lihtsalt IDE autogenniga teha getterid ja setterid valmis.

2022-09-30 08:11 UTC, harlikodasma commented on core/src/main/java/ee/tlu/evkk/core/service/maps/TranslationMappings.java
>  public class TranslationMappings {
Saab seal kasutada ka Map, Set jms tüüpi andmeid nagu mul siin tehtud on (ja on vajalik)? Näen justkui variante, et seal lihtsalt hoida muutujas stringi kujul üksikuid ridu - ei leia head näidet. Tehniliselt nad pole päris tõlked, vaid rohkem andmekollektsioon, mida kasutatakse ühes keerulises funktsioonis. Nimetasin lihtsalt selliselt, et oleks kontekstis arusaadav.

2022-09-30 17:57 UTC, mikktarvas submitted a review, later dismissed

2022-10-03 07:29 UTC, mikktarvas approved these changes

2022-10-03 08:33 UTC, merged