Feature/add texts
centre-for-educational-technology/evkk pull request #141
Opened 2023-01-31 20:13 UTC by jaagup

Sisestusvorm, lisab tekstid ja metaandmed uude tabelisse

2023-02-01 08:52 UTC, mikktarvas requested changes

2023-02-01 08:52 UTC, mikktarvas commented on db/src/main/resources/migration/versioned/V0005__Migration.sql
> +);
`call core.attach_meta_trigger('core.text_property_added');`

2023-02-02 17:53 UTC, jaagup commented on db/src/main/resources/migration/versioned/V0005__Migration.sql
> +);
Tehtud

2023-02-02 18:18 UTC, mikktarvas approved these changes

2023-02-02 20:13 UTC, merged