Wordanalyzer/click tutorial
centre-for-educational-technology/evkk pull request #144
Opened 2023-02-01 11:32 UTC by TaaviKamarik

Lisasin sõnaanalüsaatorile tuuri koos sessioonimällu salvestamisega.

2023-02-02 20:38 UTC, harlikodasma requested changes

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +  const [boxOpen, setBoxOpen] = new useState(1)
siin ka paljudes kohtades semikoolonid puudu

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +    sessionStorage.setItem('tutorial', "false")
kasuta ühtemoodi kas single quote või double quote. Rida 9 ka erinev, vb kuskil veel

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +    sessionStorage.setItem('tutorial', "false")
Kas siin loogika selline et kuni sessiooni sulgemiseni ei pakuta enam tutoriali võimalust ja uuesti külastades jälle on? On see kindlasti hea lahendus?

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +        <Box position={"absolute"} left={"20%"} top={"20%"} width={"30%"} height={"15%"} borderRadius={"10px"}
Pigem kõik stiilid eraldi css faili niipalju kui võimalik ja klassiga külge pookida kuhu vaja. Siis js fail palju puhtam ja loetavam ning lihtsam stiili muuta ja parandada vajadusel. Tee nii nagu mujal, et igal komponendil samanimeline css fail styles all ja impordi sisse

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +
Vaata igasugused lambised tühjad read ka üle

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +  function Box5() {
Kui hiljem tõlkevõtmed igalpool teksti asemele lähevad, siis suht võimatu aru saada mida teeb Box3 või Box5. Pane pigem mingid kirjeldavamad nimed neile

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/components/Tutorial.js
> +  function Box5() {
Tegelt võiks kohe juba tõlke ka kasutusse võtta uutes komponentides, pärast vaja kõike ümber teha. Vaata sõnaanalüsaatorist kuidas seda kasutatakse või küsi minult kui ei saanud aru. Ja tõlkefailides pane kõik uued võtmed tähestiku järjekorras nagu seni on tehtud

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyser.js
> +           {/* <Box style={{cursor: "pointer"}} onClick={() => { if(open === false){
Miks see commented out? Kui vaja pole siis kustuta ära

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyserParent.js
> +                                    {/*  {tabValue === 1 || tabValue === 2 || tabValue === 3 ? <Box position={"relative"} bottom={"90px"} left={"450px"} component={"span"}
Siin ka mingi suur tükk commented

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyserParent.js
> +                                        marginTop={"-50px"}
Samamoodi palju stiile, mida võiks kuhugi css faili visata. Ja vaata ka siin failis üle tühjad read

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyser.js
> +
Tühjad read siin failis ka

2023-02-02 20:38 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyser.js
> +
Pane intellij-s formatting sisse endal commit settingutest kui juba pole, siin osades kohtades formatting ka lappes. Import optimization ka kui seda pole.

2023-02-14 12:03 UTC, TaaviKamarik commented on ui/src/elle/components/Tutorial.js
> +    sessionStorage.setItem('tutorial', "false")
See on asenduslahendus seniks kuni saab kasutajaga siduda selle.

2023-02-14 17:04 UTC, harlikodasma commented
Muidu ok, aga viimane open comment ka siis veel vaja teha.

2023-02-21 08:16 UTC, merged