Improvement/word analyzer filter fix
centre-for-educational-technology/evkk pull request #153
Opened 2023-03-01 11:43 UTC by TaaviKamarik

Sõnaanalüsaatori tabelite filtrite muudatused.

2023-03-01 11:48 UTC, harlikodasma commented
@TaaviKamarik mergesin just päringu devi mis on väga suur tükk ja ilmselt sellep kukkusid osad failid konflikti - vaata üle

2023-03-09 18:38 UTC, harlikodasma commented
@TaaviKamarik hunnik console loge, tühje ridu, puuduvaid semikooloneid jne. Vaata uuesti üle kriitilise pilguga ja siis pingi uut review'd

2023-03-09 18:39 UTC, harlikodasma requested changes
Hunnik console loge, tühje ridu, puuduvaid semikooloneid jne. Vaata uuesti üle kriitilise pilguga ja siis pingi uut review'd

2023-03-14 19:43 UTC, harlikodasma requested changes

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +  const [filterValue, setValue] = useState([])
getter ja setter võiks 99% juhtudest olla kujul "myValue, setMyValue" ehk siin võiks setter olla setFilterValue. Muidu väga raske hiljem aru saada

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +  const [filtersInUse, setAppliedFilters] = useState([])
Suuremas osas uues koodis ikka semikoolonid puudu igaltpoolt

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +        value
Selle saab onelineriks taandada

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +        <FormControl size={"small"} sx={{width: 330, minWidth: 330}}>
Olenevalt olukorrast mingi üksik inline style on ok, aga 2+ võiks juba css failis olla

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +              sx={{backgroundColor: "white", width: "360px", position: "absolute", right: "-100%", zIndex: "100"}}>
Terves selles plokis ka räigelt inline stiile

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +
Selles uues koodiplokis jälle palju tühjasid ridasid

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +        value
Saab jälle taandada üheks reaks

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +        <FormControl size={"small"} sx={{width: 330, minWidth: 330}}>
Stiilid peitu

2023-03-14 19:43 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +            <Accordion sx={{border: "none", boxShadow: "none", width: "68px", height: "48px"}}>
Stiilid peitu

2023-03-14 19:56 UTC, harlikodasma commented
@TaaviKamarik tee enne pull kui hakkad muudatusi tegema, kuna lahendasin sinu eest siin branchis ühe pisikese merge conflicti ära

2023-03-15 14:58 UTC, harlikodasma requested changes

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +  const [filtersInUse, setAppliedFilters] = useState([]);
Need võiks ka matchida omavahel

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +            <Box className="rakendatud-filtrid-box">Rakendatud filtrid: {AppliedFilters()} </Box> : null}</Box>
Klassi nimed võiks samas stiilis olla ehk siis inglise keeles

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +            <Button className="Popover-button" aria-describedby={popoverId} variant="contained" onClick={handlePopoverOpen}><FilterAltIcon fontSize="large"/></Button>
Ja ka samas kirjapildis ehk näiteks kebab-case (sidekriipsudega eraldatud, algab väikese tähega)

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/styles/Syllables.css
> +
Kui juba muutmiseks läheb, siis tühi rida siin

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/styles/Syllables.css
> +.popover-box{
Pane auto-formatting sisse endal intellij-s commitimisel, see parandab palju koledaid asju automaatselt ära. Nagu nt siin, { võiks mitte hõõruda nime ehk seal võiksid igalpool tühikud vahel olla. Aga parandab veel igasuguseid asju

2023-03-15 14:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
Soovitan alati enne review pingimist teha nii, et PR üles ja siis vaatad ise githubis ka veel "files changed" läbi. Märkad ilmselt mitmeid asju (tühjad read, semikoolonid, console logid jne jne). Siis läheks kogu PR kiiremini läbi kui sellised asjad juba enne minu vaatamist korras oleks.

2023-03-15 14:59 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
>                 style={{marginRight: 'auto', marginLeft: 'auto', borderBottom: 'solid 1px', width: '100%'}}>
Tõsta need ja juba klassi, kui muutma hakkasid

2023-03-15 14:59 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
>               style={{marginRight: 'auto', marginLeft: 'auto', borderBottom: 'solid 1px', width: '100%'}}>
Tõsta need ka juba klassi, kui muutma hakkasid

2023-03-22 11:28 UTC, TaaviKamarik commented
Ma loodan, et nüüd on enam vhem OK. Parandasin ära, ja vaatasn üle pärast ja parandasin veel veits.

2023-03-22 22:06 UTC, harlikodasma requested changes

2023-03-22 22:06 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyserParent.js
> +                                  {/*{tabValue !== 0 ? <Tutorial/> : null}*/}
Kui kindlasti tahad jätta kommenteeritud rea sisse, siis pane ka mingi todo kommentaar juurde, et sonari ja ctrl+f abil leiaks lihtsasti poolikud kohad üles

2023-04-02 14:34 UTC, TaaviKamarik commented on ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
> +          <Button className="popover-button" aria-describedby={popoverId} variant="contained"
Mul on reformat, rearrange ja optimize imports sees, aga see ei muuda neid ära.

2023-04-02 15:07 UTC, TaaviKamarik commented
Ehk on nüüd kõik. Fingers crossed.

2023-04-02 20:45 UTC, harlikodasma approved these changes

2023-04-02 20:45 UTC, merged