Corrector/style changes
centre-for-educational-technology/evkk pull request #172
Opened 2023-04-19 11:39 UTC by TaaviKamarik

2023-04-19 12:58 UTC, harlikodasma requested changes

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +
Pole vaja tühja rida siia

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +
Siia ka pole vaja

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +import TextUpload from "../wordanalyser/textupload/TextUpload";
See import küll vist õige pole, töötab sul ja IDE ei anna erroreid?

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    var degreeValue
vari asemel kasutada let

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            {/*this.renderTasemed()*/}
Kui pole enam vaja siis kustuta ära

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +          </Box>) : <div>Tekst liiga lühike</div>) : ""}</Box> : "Tekst on liiga lühike"}</Box>
Mis värk siin toimub :D

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    return <Box component={"span"} width={"auto"}>{this.state.kordab ?
Kogu see ternary operaatorite chainimine üksteise sisse on väga messy ja koodi lugeda jube halb. Äkki saaks kuidagi lihtsamaks teha, nt erinevatele tingimustele vastava returni sisu panna omaette funktsioonidesse?

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                  label="Korrektuur"
label erineb

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                    {/*<table width={"80%"}>
Kui pole vaja siis kustuta ära

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +
Ebavajalik

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +
Ebavajalik

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +.border-bottom {
See kehtib siin ka muude asjade kohta, nt tab-container, wrapper, pointer-hover jne

2023-04-19 12:58 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +#textarea {
Samuti sellised generic IDd on halb, sest ID peaks olema strictly unique, aga textareasid pigem on rohkem kui üks. Võiks panna mingid spetsiifilisemad IDd või üldse klassidega lahendada seda

2023-07-27 12:49 UTC, harlikodasma requested changes

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/bootstrap.css
> +.corrector-border-bottom {
Bootstrapi ei tohi muuta, tee see klass enda css faili

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
>  .punataust {
Võiks renameda selle selectori

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
>  textarea:hover {
Need reeglid peaks rakenduma siis kõigile inputidele ja textarea-dele, tuleks lahendada kindlate klassi nimedega sest pärast suur peavalu miks ja kust need tulevad

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +.margitud-container {
Võiks renameda selle selectori

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +.corrector-margitud {
Võiks renameda selle selectori

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.css
> +.tase-box-1 {
Võiks renameda selle selectori

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +    const [sisu, setSisu] = useState(props.sisu);
Võiks mitte kasutada eestikeelseid nimetusi

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +    const [vastus, setVastus] = useState(props.vastus);
Võiks mitte kasutada eestikeelseid nimetusi

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +    const [jrk, setJrk] = useState(props.jrk);
Võiks mitte kasutada eestikeelseid nimetusi

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                        justifyContent="center"
Neid stiile css klassi ei saa tõsta?

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                  {sm[i].replace(/^[^0-9a-zA-ZõäöüÕÄÖÜ]+/, '').replace(/[^0-9a-zA-ZõäöüÕÄÖÜ]+$/, '')}
Mida ta siin 2x replaceb? Võiks kasutada kas consti nende regexite jaoks või veel parem, luua meetod mis mõlemad replaced ära teeb ja kutsuda seda välja, oleks palju ilusam ja lihtsam

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                  {vm[i].replace(/^[^0-9a-zA-ZõäöüÕÄÖÜ]+/, '').replace(/[^0-9a-zA-ZõäöüÕÄÖÜ]+$/, '')}
Mida ta siin 2x replaceb? Võiks kasutada kas consti nende regexite jaoks või veel parem, luua meetod mis mõlemad replaced ära teeb ja kutsuda seda välja, oleks palju ilusam ja lihtsam

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                        props.asenda(sm, vm, i);
asenda -> inglise keelde

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                    onClick={() => props.eiAsenda(sm, vm, i)}
eiAsenda -> inglise keelde

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                        minHeight: 25,
Stiilid css klassi?

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +                                        minHeight: 25,
Stiilid css klassi?

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +const WordClick = (props) => {
Saaks teha `export default function WordClick(props) {` ja siis kustutada rida 192 ära

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +});
Paneks siia vahele ühe tühja rea

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/WordClick.js
> +
Selle tühja rea võtaks maha

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +        info.col1 = row[0];
Siin mingi kahtlane taande error tekkinud

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/Syllables.js
> +      let output = formattedSyllables.map((row) => {
See peaks ka tegelt olema nii nagu varem

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
Sul vist commitimisel auto-formatting ikka ei toimi? Kui ma ise formattisin, siis muutis 641 rida ära :D igast pisiprobleeme nagu nt semikoolonid ja taanded kogu failis

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +import WordClick from "./WordClick";
Peale importe paneks vähemalt ühe tühja rea

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const [keerukusvastus, setKeerukusvastus] = useState([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
Tulebki keerukusele ja mitmekesisusele nii koledal kujul vastused backist? Selle peaks küll ära muutma :D

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const [alasisu, setAlasisu] = useState('');
Kõik need stated paneks inglise keelde

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const puhasta2 = (sona) => {
Meetodite nimed samamoodi no-no eesti keeles

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const kysi6 = () => {
Need kysi1-6 pole üldse hea naming scheme ja kui midagi sarnast jätta, siis nad võiks koodis ka olla õiges järjekorras mitte 1, 2, 5, 6, 3 jne

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            const response = await fetch("/api/texts/korrektuur", {
Kas sul on custom loading animationid igal tabil vms? Kui ei ole, siis oleks hea kasutada fetch() asemel loadFetch(), sest see teeb ise loaderi ja näitab kasutajale normaalsel kujul viga, kui midagi valesti läks

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            console.error(error);
Need console errorid suht lambikad, kasutaja neid nkn vaatama ei lähe ja meil neist ka abi pole

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                        <span key={"sm" + i}>
Siin ka formatting väga lappes, loodetavasti läheb korda peale auto-formattingut

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        if (tasemevastus.length !== 1 && tasemevastus[0] !== undefined) {
`tasemevastus[0] !== undefined` vist piisaks lihtsalt `tasemevastus[0]` sest see peaks undefined checki tegema? Proovi üle aga imo on nii

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            let val1 = parseInt((tasemevastus[0][0] * 100 * 3.6).toFixed(0), 10);
Nende arvutamiseks võiks teha eraldi meetodi mitte dubleerida sama asja 4x ja siis lasta nad kõik sealt meetodist läbi. Ja `let` peaks kasutama ainult siis kui andmed muutuvad, muidu `const`

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                            <Box id={error[0]} display="inline-flex" borderRadius="10px" maxWidth="min-content"
Stiilid cssi

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                                            sx={{borderRadius: 30, padding: 0, minHeight: 30, minWidth: 30}}
Stiilid cssi

2023-07-27 12:49 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                                            sx={{borderRadius: 30, padding: 0, minHeight: 30, minWidth: 30}}
Stiilid cssi

2023-07-28 08:12 UTC, TaaviKamarik commented on ui/src/bootstrap.css
> +.corrector-border-bottom {
Ma ei tea, miks see muutunud oli. Correctori klassis oli sellenimeline fail juba olemas. Pole Bootstrapi omaarust muutnud.

2023-07-28 08:15 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/Correction.css
>  .punataust {
Eemaldasin. Polnud kasutatudki.

2023-07-31 15:42 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/Correction.component.js
> +            let val1 = parseInt((tasemevastus[0][0] * 100 * 3.6).toFixed(0), 10);
see degreeValue väärtuys muutub if sees

2023-07-31 16:10 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/Correction.component.js
> +    const [keerukusvastus, setKeerukusvastus] = useState([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
See vastus tuleb backist Arrayna ja

2023-08-10 14:39 UTC, harlikodasma requested changes

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const [levelAnswer, setLevelAnswer] = useState(['algusväärtus']);
'algusväärtus' võiks ka kuidagi muudmoodi nimetatud olla või kasutatud siin mingit teist andmetüüpi if possible

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const [openCard, setOpenCard] = useState('korrektuur');
äkki saab siin sama teha nagu 'algusväärtus'?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const clean2 = (word) => {
Mis vahe on täpsemalt clean ja clean2, on neid mõlemaid ikka vaja? Teisiti nimetada kuidagi?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            return word.replace(/^[^0-9a-zA-ZõäöüÕÄÖÜ]+/, '').replace(/[^0-9a-zA-ZõäöüÕÄÖÜ]+$/, '');
Mis selle 2x replace mõte on täpsemalt?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +    const alaMuutus = (event) => {
Võiks ka olla english

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        if (word !== undefined && word !== "") {
Seda checki saaks lihtsustada `if (!!word)`

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        let tempArray = replyCode.map((value) => {
const?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        for (let i = 0; i < content.length; i++) {
Kas siin ei saaks lihtsalt joinida kõiki content.lengthe ja vajadusel trimida hiljem lõputühik maha?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        for (let i = 0; i < content.length; i++) {
Kas siin ei saaks lihtsalt joinida kõiki content.lengthe ja vajadusel trimida hiljem lõputühik maha?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        let tempArray = replyCode.map((value) => {
const

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        const newContent = content;
128-130 read tunduvad mõttetud, peaks saama real 137 ju lihtsalt `setLevelText({tekst: content})` või midagi taolist

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        obj["tekst"] = content;
Siin sama asi nagu eelmine comment

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            console.log(t)
console log

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            const response = await fetch("/api/texts/korrektuur", {
Katseta korra mis juhtub kui loadFetchi kasutad, võiks võimalusel olla globaalselt igalpool sarnane loaderi loogika ja välimus. Äkki sobib siia ka

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        try {
See fetchi ümbritsemine tryga on kahtlane, pigem võiks kasutada fetchi peal .then() meetodit, nagu LoadFetch.js failis. Tuleb kompaktsem, ei pea catchima ja exceptioneid loopima

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        const obj = {
Seda ka pole mõtet eraldi eriti luua, pigem inline seal kus kasutatakse

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            let vm = data[0].split(" ");
189 ja 190 constideks või veel parem, need inlineda otse 191 ja 192 sisse

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +            for (let i = 0; i < answer.length; i++) {
tavalised for loopid võiks olla ainult erandjuhtudel kasutuses, pigem teha foreachiga

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +        setChangesCode(<div>{changes.length > 0 ? changes : "puuduvad"}</div>);
Võiks ju booleani kasutada mitte stringi kujul checkida mingit conditionit hiljem?

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                </Box>) : ("Tekst on liiga lühike")}
Kogu selles suures return plokis on palju korduvaid inline stiile mida võiks css klassidesse tõsta. Isegi kui pole korduv ja rohkem kui 1 rule, võiks ka olla css klass

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                         className="error-conteinar-outer">
typo, container

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
> +                                </Button>
siin suures plokis ka stiile panna css klassidesse

2023-08-10 14:39 UTC, harlikodasma commented on ui/src/elle/tools/correction/Correction.component.js
Kui nüüd on klassipõhisest komponendist üle mindud funktsionaalsele, siis faili enda võiks ka renameda `Correction.js`

2023-08-22 09:08 UTC, TaaviKamarik commented on ui/src/bootstrap.css
Rollbackisin ära oma keskkonnas

2023-09-06 12:32 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/Correction.js
> +    fetch("/api/texts/keeletase", {
Need tavalised fetchid jooksevad nii-öelda taustal. Kui ma loadFetch paneksin nende asemele, siis iga kord kui korrektuuri vaates sõna parandada tekib loading overlay sekundiks, kuna need teised tabid fetchivad alati uuesti, kui sõnakorrektori vaates sõna parandada.

2023-09-06 18:39 UTC, harlikodasma requested changes

2023-09-06 18:39 UTC, harlikodasma commented on ui/src/bootstrap.css
Ikka jama. Proovi näiteks nii, et copy käsitsi algne seis ja lülita korraks välja code auto-reformatting, et ühtegi muudatust ei tuleks commiti tehes. Siis peaks saama tagasi normaalseks.

2023-09-13 15:33 UTC, harlikodasma requested changes
Ikka sama :D ei tohiks bootstrapi üldse näidata muudetud failide all

2023-09-13 17:01 UTC, mikktarvas commented
https://stackoverflow.com/a/37972822

2023-09-24 21:32 UTC, harlikodasma approved these changes

2023-09-24 21:34 UTC, merged