480 eksamitekstile lisatud korpus
centre-for-educational-technology/evkk pull request #196
Opened 2023-09-07 10:52 UTC by jaagup

2023-09-07 21:54 UTC, harlikodasma approved these changes
Teinekord märgi mind review tegijate alla, muidu mulle ei tule teadet

2023-09-07 21:55 UTC, harlikodasma requested changes
Failinimi peaks algama R__0006, kuna 4 ja 5 on vahepeal juurde tekkinud

2023-09-07 21:57 UTC, harlikodasma commented
Branchi nimi väga õige, hästi! Muutsin PRi nime ära, see võiks ka edaspidi sellist formaati kasutada.

2023-09-08 04:38 UTC, jaagup commented
Nüüd IntelliJ kaudu nimi muudetud

2023-09-08 08:54 UTC, harlikodasma approved these changes

2023-09-08 08:54 UTC, merged