Esilehe muutused uus kujundus
centre-for-educational-technology/evkk pull request #204
Opened 2023-10-02 08:33 UTC by TaaviKamarik

Viimane monster PR. Edaspidi ma sind nii suurte pushidega ei piina.

Navbar ja Query vajavad veel eraldi optimeerimist, aga need hetkel ei sega lehe tööd. Tulen nende juurde hiljem tagasi.

2023-10-02 17:42 UTC, harlikodasma requested changes

2023-10-02 17:42 UTC, harlikodasma commented on ui/src/elle/pages/Tools.js
>  function Tools() {
Võiks siin ja edaspidi kasutada kuju "export default function Tools() {", siis ei ole vaja kõige all eraldi "export default" teha

2023-10-02 17:42 UTC, harlikodasma commented on ui/src/elle/pages/Tools.js
> +  const [tabPage, setTabPage] = React.useState(page);
Otse useState importiga

2023-10-02 17:42 UTC, harlikodasma commented on ui/src/elle/pages/Tools.js
> +              Tööriista kasutamiseks tuleb vasakult menüüst valida analüüsitav tekst või tekstid!
Tõlkimata tekst

2023-10-02 17:42 UTC, harlikodasma commented on ui/src/elle/components/InfoElementTabCard.js
> +      <p className="tool-button-text">{props.toolTitile}</p>
props.toolTitle typo, igalpool mujal ka siis muuta

2023-10-02 17:42 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
>    common_word_analysis: 'Sõnaanalüüs',
Seda enam ei kasutata? Siis võiks eemaldada (mõlemas failis). Oli muidu kokkulepe et Mustrid -> Mustrileidja ja Sõnaanalüüs -> Sõnaanalüsaator?

2023-10-02 17:46 UTC, harlikodasma commented on ui/src/elle/components/HeroElement.js
> +import React from 'react';
Kuna tekkis palju erinevaid komponente avalehe moodustamiseks, siis need võiks sorteerida, pannes nad components kausta sees omaette kausta kokku, nt kaust "home"

2023-10-02 17:47 UTC, harlikodasma commented on ui/src/elle/pages/Home.js
>  function Home() {
Võiks siin ja edaspidi kasutada kuju "export default function Home() {", siis ei ole vaja kõige all eraldi "export default" teha

2023-10-04 13:23 UTC, TaaviKamarik commented on ui/src/elle/translations/et/translations.js
>    common_word_analysis: 'Sõnaanalüüs',
Sõnaanalüüs on sõnaanalüsaatoris kasutusel.

2023-10-11 12:17 UTC, TaaviKamarik commented
Ma vaatan kõik UI Warningud eraldi ticketina üle.

2023-10-16 20:02 UTC, harlikodasma commented
Nuppudesse ei mahu ingliskeelne tõlge ära:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/b4eb8d48-0722-4b33-884c-64392470d2b8)

2023-10-16 20:03 UTC, harlikodasma commented
Juba pisut kitsama ekraani peal sõidab tekst pildile sisse:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/28558c22-a0fb-4bd7-9835-25efefffff80)

2023-10-16 20:06 UTC, harlikodasma commented
Osadel tõlgitud rakendustel on ingliskeelses UIs eestikeelsed screenshotid, nt "Sõna kontekstis"

2023-10-16 20:28 UTC, harlikodasma commented
Burgeri ikoon peaks olema veits rohkem paremale joondatud, muidu hakkab ta peaaegu kohe ilmudes pildi sisse clippima:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/bcdee849-db4b-4338-8e75-ac276035effe)

2023-10-16 20:29 UTC, harlikodasma commented
Teksti loovutamise aknas peaks üleval ja all rohkem ruumi olema:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/11b2d894-be1c-4385-a103-b438c160a2dc)

2023-10-16 20:34 UTC, harlikodasma commented
Sarnaselt teistele vaadetele peaks siin ka footeri ja main elemendi vahel ruumi olema:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/2f8766f9-d349-4fb1-883c-28cf1882f25c)

2023-10-16 20:36 UTC, harlikodasma requested changes

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/pages/Tools.js
> +                <Tab label="Mustrileidja" onClick={() => toolSelect('clusterfinder')} value="5"/>
Labelid on kõik tõlkimata, keelt vahetades jäävad samaks

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/tools/wordcontext/WordContext.js
> -  const removeUrlParams = () => {
Miks selle eemaldamine vajalik oli? Funktsionaalsus mingi ime läbi isegi jäi tööle, aga nüüd liikudes sõnaloendist kontekstide rakendusse jäävad request paramid URLi alles, mis on suht kole ja segadusttekitav

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/pages/query/Query.js
> +      {/*{(corpusTextsSelected > 0 || ownTextsSelected) && <>
Need chipid peaks alles jääma, vajalik funktsionaalsus

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/pages/query/Query.js
> +                 onClick={() => navigate('adding')}
Seda nuppu pole enam vaja vist, kuna nüüd on ta igal lehel paremas ääres

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/translations/en/translations.js
> +  common_publish_your_text: 'Publish your text',
See peaks imo vanal kujul olema, conflict sai vist valesti mergetud

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/translations/en/translations.js
> +  upload_button: 'Upload',
See ei peaks siin olema imo, valesti mergetud

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
> +  upload_button: 'Laadi üles',
See ei peaks siin olema imo, valesti mergetud

2023-10-16 20:36 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
> +  common_publish_your_text: 'Loovuta tekst',
See peaks imo vanal kujul olema, conflict sai vist valesti mergetud

2023-10-18 14:38 UTC, TaaviKamarik commented on ui/src/elle/tools/wordcontext/WordContext.js
> -  const removeUrlParams = () => {
See koodijupp lõhkus mul kontekstileidja ära.

2023-10-18 14:56 UTC, TaaviKamarik commented on ui/src/elle/translations/en/translations.js
> +  common_publish_your_text: 'Publish your text',
"Publishing text" pole grammatiliselt õige. Panin "Text publishing"

2023-10-18 15:38 UTC, TaaviKamarik commented
Klasterdaja ja tekstihindaja on tõlkimata. Nende UI vaated jäid ainult eestikeelseks esialgu.

2023-10-21 10:27 UTC, harlikodasma commented
Siin on midagi viimase commitiga lappama läinud:
![image](https://github.com/centre-for-educational-technology/evkk/assets/70939399/37f8e524-8a8e-41aa-8b13-0df95d8d06a5)

2023-10-21 10:28 UTC, harlikodasma requested changes
Need viimased pisiasjad veel korda saab siis peaks kõik ok olema ja ready for merge (üleval on üks eraldi comment pildiga veel)

2023-10-21 10:28 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
> +  query_results_saved_for_analysis_corpus_plural: 'korpuse teksti',
Siin vist pole ühelgi vaja tühikut ette, kuna number on eelnevalt mingi teise elemendi sees mis paneb vahe sisse. Pane mõlemas tõlkefailis kõik need 4 võtit siis ilma eesoleva tühikuta

2023-10-21 10:28 UTC, harlikodasma commented on ui/src/elle/components/home/InfoElement.js
> +
Kui juba muudad siis võid siit lisarea ära võtta :D

2023-10-21 10:39 UTC, harlikodasma commented on ui/src/elle/tools/wordcontext/WordContext.js
> -  const removeUrlParams = () => {
Proovisin ja tundub, et probleemiks on see, et meetodit kutsutakse liiga vara välja. Panin callimise reale 189 (peale if-else plokke, viimaseks asjaks .then sisse) ja nüüd tundub toimivat.
Ilma selle koodita näitab URLis parameetreid siis, kui lähed sõnaloendis mingi sõna menüüd avades edasi kontekstide vaatesse.
Lisa see tagasi ja proovi erinevaid versioone, kas tundub korrektselt töötavat.

2023-10-21 13:17 UTC, harlikodasma approved these changes

2023-10-21 13:17 UTC, merged