ELLE-252
centre-for-educational-technology/evkk pull request #219
Opened 2023-10-22 18:04 UTC by TaaviKamarik

Tegin tagasinupu ning päringud jäävad meelde. Lisaks parandasin Esilehel Hero nupu.

2023-10-22 18:07 UTC, TaaviKamarik commented
@harlikodasma unustasin commentisse lisada, et parandasin sünaanalüsaatori ühendamisel ka ühe probleemi ära, mis Kais tõstatas. See oli nii väike asi, et eraldi ticketit polnud mõtet teha.

2023-10-22 22:58 UTC, harlikodasma commented
> @harlikodasma unustasin commentisse lisada, et parandasin sünaanalüsaatori ühendamisel ka ühe probleemi ära, mis Kais tõstatas. See oli nii väike asi, et eraldi ticketit polnud mõtet teha.

Kas klastrileidja kohta oli sama viga? Kui jah, siis kas see parandatakse veel eraldi?

2023-10-22 22:58 UTC, harlikodasma requested changes

2023-10-22 22:58 UTC, harlikodasma commented on ui/src/elle/tools/wordanalyser/WordAnalyser.js
> +          console.log(result)
Maha võtta

2023-10-22 22:58 UTC, harlikodasma commented on ui/src/elle/pages/query/Query.js
> +                </div>
Saaks vähema koodi duplicationiga:
* condition check oleks nt ``(alert || noResultsError)``
* Alert tagi sees olev tekst oleks ternary operatoriga nt ``noResultsError ? 'query_results_no_texts_found' : 'error_query_no_subcorpus_picked'``, sellega peaks saama t() meetodi sees mängida, millist stringi talle ette anda

2023-10-22 22:58 UTC, harlikodasma commented on ui/src/elle/pages/query/Query.js
> +  const [previousSelectedIds, setPreviousSelectedIds] = useState({})
Suva praegu aga jälle semikoolonid puudu. Tuleta homme meelde, vaatame su IDEA settingud üle, et kõik see automaatselt toimuks.

2023-10-22 22:58 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
> +  query_change_chosen_corpuses: 'Muuda valitud korpuseid',
Siin peaks kindlasti teistmoodi sõnastama, et mitte rõhuda ainult korpuste valikutele. Nt "Muuda päringu parameetreid" vms. Küsin Kaisilt sõnastust. Sama asi ingliskeelse vaste kohta.

2023-10-23 06:55 UTC, harlikodasma commented on ui/src/elle/translations/et/translations.js
> +  query_change_chosen_corpuses: 'Muuda valitud korpuseid',
Kais ütles, et võiks olla "Muuda otsingut" ja inglise keeles siis midagi taolist

2023-10-23 13:42 UTC, TaaviKamarik commented
> > @harlikodasma unustasin commentisse lisada, et parandasin sünaanalüsaatori ühendamisel ka ühe probleemi ära, mis Kais tõstatas. See oli nii väike asi, et eraldi ticketit polnud mõtet teha.
> 
> Kas klastrileidja kohta oli sama viga? Kui jah, siis kas see parandatakse veel eraldi?

Tegin selle ka ära selle PR raames

2023-10-23 15:37 UTC, harlikodasma approved these changes

2023-10-23 15:37 UTC, merged