ELLE 280 | grammar worker speller only
centre-for-educational-technology/evkk pull request #304
Opened 2024-06-30 19:15 UTC by TaaviKamarik

2024-08-12 08:23 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/tabviews/vocabularytab/VocabularyTab.js
> +        </div>
T

2024-09-02 21:14 UTC, harlikodasma requested changes
Tee praegused commentid ära, viimase asja vaatame veel koos üle ja siis peaks saama esialgu edasi liikuda. Jätkupiletid, mis järgmisena ette võtta:

https://evkk-elle.atlassian.net/browse/ELLE-312
https://evkk-elle.atlassian.net/browse/ELLE-311
https://evkk-elle.atlassian.net/browse/ELLE-310

2024-09-02 21:14 UTC, harlikodasma commented on docker/compose/docker-compose.base.yml
> +    container_name: grammar-worker-server
image ja container_name võiks mõlemad olla evkk-grammar-worker-server, et olla teistega ühes stiilis.
Siis tuleks muuta ka build.sh skripti ning docker-compose failis container_name ja nimetatav Dockerfile.
**Aga jäta nii siin kui docker-compose failis service name ikkagi selliseks, et aadressiks jääks grammar-worker-server:5400 (lühem variant on ka teistel konteineritel).**

2024-09-10 19:45 UTC, harlikodasma commented on stanza-server/grammar_fetches.py
> +        print('None')
print sisse jäänud

2024-09-10 19:45 UTC, harlikodasma commented on stanza-server/grammar_fetches.py
> +        print(response)
print sisse jäänud

2024-09-10 19:46 UTC, harlikodasma commented on docker/compose/docker-compose.base.yml
> +    image: grammar-worker-server
Miks see nimi uuesti ilma evkk prefixita?

2024-09-25 20:09 UTC, harlikodasma commented on ui/src/elle/tools/correction/tabviews/complexity/ComplexityTab.js
> +    return newArray.map((complexityWord, index) => index === newArray.length - 1 ? complexityWord : `${complexityWord} / `);
Lihtsustaks kogu meetodit, näiteks selliselt:
`return answer
  .split('/')
  .map(t)
  .map((complexityWord, index, array) => 
    index === array.length - 1 ? complexityWord : `${complexityWord} / `
  );`

2024-09-25 20:11 UTC, harlikodasma commented on ui/src/elle/tools/correction/tabviews/correction/components/ErrorAccordion.js
> +        if (errorProperties[1].length > 1 && errorProperties[1][0].span.start > errorProperties[1][errorProperties[1].length - 1].span.start) {
Extractiks if lause eraldi meetodisse ja annaks sellele nime, mis seletaks, mida see kontroll teeb. Ma hetkel peale vaadates ei saa midagi aru, mis siin toimub

2024-09-25 20:11 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +    console.log(lemma, !EXCLUSION_WORDS.includes(lemma), complexityAnswer[index]);
console log

2024-09-25 20:12 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +  });
Siin saaks ka lihtsamalt:

![image](https://github.com/user-attachments/assets/45a9cff2-e6ab-4bd0-af27-e94116d88943)

2024-09-25 20:15 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +  duplicateIndexes.forEach((wordValue) => {
Üksikule paramile pole ümbritsevaid sulge vaja

2024-09-25 20:16 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +      } else if (/both-sentence-color/.test(match)) {
Esimene ja teine if tagastavad täpselt sama väärtuse, peaks saama tingimused ühendada?

2024-09-25 20:16 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +      console.log(tempText);
console log

2024-09-25 20:16 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +  console.log();
console log

2024-09-25 20:17 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +    let regex1 = new RegExp(`(<span[^>]*>\\s*)?\\b${sentenceWords[wordValue]}\\b(\\s*</span>)?`, 'g');
Mingi parem nimetus äkki kui regex1?

2024-09-25 20:18 UTC, harlikodasma commented on ui/src/elle/translations/en/translations.js
> +  corrector_complexity_long_phrases: 'Long sentences',
Tõlkevõti ei ole vist enam adekvaatne? Peaks äkki olema `corrector_complexity_long_sentences`?

2024-09-25 20:19 UTC, harlikodasma requested changes
Lisatud commentid

2024-09-25 20:23 UTC, harlikodasma commented on ui/src/elle/tools/correction/tabviews/correction/hooks/useProcessTextCorrections.js
> +          let newSpan = correction.span.value.split(' ').reverse();
Ei toimu mutationit, võiks const olla

2024-09-25 20:27 UTC, harlikodasma commented on ui/src/elle/tools/correction/components/CorrectionToggleButtonGroup.js
> +              });
Kas see hunniku asjade väljakutsumise duplicatemine jäi hetkel ainult kokku kahte kohta (siia ja CorrectionButton.js)? Ja neil peabki veidi erinev implementatsioon olema (teises kohas setRequestingText on väljaspool theni)?

Seda peaks ka veel ühtsustama.

2024-09-25 20:36 UTC, harlikodasma commented on grammar-worker-server/grammar-worker.py
> +    from gec_worker import MultiCorrector
Siin peaks saama 3 importi ühele reale panna: `from gec_worker import GEC, Speller, MultiCorrector, read_gec_config, read_speller_config`

2024-09-26 16:33 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/tabviews/vocabulary/constants/constants.js
> +export const commonLemmas = ['olema', 'ja', 'see', 'tema', 'mina', 'ei', 'et', 'kui', 'mis', 'ka', 'saama', 'ning', 'oma', 'aga', 'sina', 'pidama', 'siis', 'või', 'kes', 'aasta', 'võima', 'üks', 'nii
Jah.

2024-09-26 16:56 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/components/CorrectionToggleButtonGroup.js
> +              });
Implementatsiooni saab ühtlustada. Kolmes kohas on see.

2024-09-26 17:35 UTC, harlikodasma commented on stanza-server/grammar_fetches.py
> +        print('None')
See pole tehtud

2024-09-26 17:35 UTC, harlikodasma commented on stanza-server/grammar_fetches.py
> +        print(response)
See pole tehtud

2024-09-26 17:38 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +      } else {
else sisse pole vaja wrappida, saab taandeid vähemaks kui panna lihtsalt pärast if-i see, sest if sees toimub juba return

2024-09-26 17:53 UTC, harlikodasma commented on docker/compose/docker-compose.base.yml
> +    image: grammar-worker-server
Lahendamiseks jätkupilet https://evkk-elle.atlassian.net/browse/ELLE-314

2024-09-26 18:13 UTC, harlikodasma commented on ui/src/elle/tools/correction/components/CorrectionToggleButtonGroup.js
> +              });
Jätkupilet selle lahendamiseks: https://evkk-elle.atlassian.net/browse/ELLE-315

2024-09-26 20:24 UTC, harlikodasma commented on ui/src/elle/translations/en/translations.js
> +  corrector_vocabulary_statistics_different_words: 'Different words',
Tõlkevõtit sa koodis vist ära ei vahetanud?

2024-09-26 21:52 UTC, harlikodasma commented on common/src/main/resources/services/demo.properties
> +CLUSTER_FINDER        = http://praktika1.cs.tlu.ee:9999/clusterfinder
Siin peab olema https://praktika1.cs.tlu.ee/clusterfinder

2024-09-26 21:52 UTC, harlikodasma commented on common/src/main/resources/services/demo.properties
> +EVKK_PUBLIC_API       = http://praktika1.cs.tlu.ee:9999/api
Siin peab olema https://praktika1.cs.tlu.ee/api

2024-09-26 21:54 UTC, harlikodasma commented on common/src/main/resources/services/local.properties
> +EVKK_UI               = http://localhost:3000
Pane kõigis kolmes (demo, local, prod) kõik propertied samasse järjekorda

2024-09-26 21:56 UTC, harlikodasma commented on stanza-server/server.py
> +        "uuskeeletase": predict_level(model, scaler, tekst),
Vb juba küsisin aga "keeletase" ja "uuskeeletase" on mõlemad vajalikud ja kasutuses?

2024-09-26 22:05 UTC, harlikodasma requested changes
Veel mõned kommentaarid

2024-09-27 06:18 UTC, TaaviKamarik commented on stanza-server/server.py
> +        "uuskeeletase": predict_level(model, scaler, tekst),
See uus veel ei ole kasutuses. Ma pean Kaisiga arutama, mida ta täpselt tahab. Me vahetame selle vana mudeli uue vastu välja ilmselt.

2024-09-27 06:52 UTC, harlikodasma approved these changes

2024-09-27 06:54 UTC, merged