Harvade sõnade bugiparandus.
centre-for-educational-technology/evkk pull request #334
Opened 2024-11-04 07:25 UTC by TaaviKamarik

Fix fir word repetition marking bugs.

2024-11-05 16:23 UTC, harlikodasma commented
@TaaviKamarik branchi nimi võiks ka piletit sisaldada, kas feature/ELLE-321 või bugfix/ELLE-321 näiteks

2024-11-05 16:34 UTC, harlikodasma requested changes

2024-11-05 16:34 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +export const getRepetitions = (grammarAnswer) => {
Seda kõike saaks backis teha ju? Sul veel eraldi task, et seda kõike backi liigutada. Ära fronti juurde tee :D

2024-11-05 16:34 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +const checkSameSentenceRepetition = (repetitionArray) => {
See samamoodi + siin mingid chatgpt kommentaarid + filtris ja flatMapis "key" unused

2024-11-05 16:34 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +const processSameWordsForNextSentence = (array, prevArray) => {
Sellega sama?

2024-11-05 16:34 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> +const checkBothSentenceRepetition = (repetitionArray, prevArray) => {
Ja sellega?

2024-11-05 16:34 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyCalculations.js
> +export const calculateUncommonWords = (complexityAnswer) => {
Tervet seda faili ei tahaks ka siis juba pigem backi viia? Tundub suht mõttetu frondis neid muuta, et siis järgmise pileti raames uuesti ümber teha ja muusse keelde viia implementatsioon

2024-11-11 17:55 UTC, harlikodasma requested changes

2024-11-11 17:55 UTC, harlikodasma commented on core/src/main/java/ee/tlu/evkk/core/service/dto/TextWithComplexity.java
> +  private Object korrektori_loendid;
Java standard on camelCase mitte snake_case, see peaks olema korrektoriLoendid

Kui sul on probleeme et pythonist tulev snake_case ei mapi ennast camelCaseks ümber, siis aitama peaks @JsonProperty("korrektori_loendid") annotatsioon. Ära kindlasti pythonit sellepärast camelCaseks muuda :D

2024-11-11 17:55 UTC, harlikodasma commented on ui/src/elle/tools/correction/util/VocabularyCalculations.js
>  export const calculateAbstractWords = (abstractAnswer, complexityAnswer) => {
Kas kõik need allesjäänud calculate meetodid siin on plaanis ELLE-312 pileti raames backi viia?

2024-11-11 17:55 UTC, harlikodasma commented on core/src/main/java/ee/tlu/evkk/core/service/dto/TextWithComplexity.java
> +  private Object korrektori_loendid;
Vaata et siis muud usaged ka ära vahetad, vist oli frondis sul kasutatud seda snake_case kuju

2024-11-11 19:15 UTC, TaaviKamarik commented on ui/src/elle/tools/correction/util/VocabularyCalculations.js
>  export const calculateAbstractWords = (abstractAnswer, complexityAnswer) => {
Jap. Ma teen need ELLE-312 raames

2024-12-08 21:33 UTC, harlikodasma approved these changes

2024-12-08 21:33 UTC, merged