Clusterfinder improvements
centre-for-educational-technology/evkk pull request #40
Opened 2021-11-28 09:42 UTC by kliiva5

* Added the missing "parsed" parameter to the clustering request (in order to skip duplicate marking)
* Fixed some translation typos
* Added support for checking the "by frequency" sorting option by default in the front end

2021-11-29 09:24 UTC, mikktarvas approved these changes

2021-12-10 07:29 UTC, mikktarvas approved these changes

2021-12-30 15:49 UTC, kliiva5 commented
Tegelen veel filtreerimise parandustega - üritan lähipäevil siia ülesse saada veel need (ehk pole veel mõtet mestida)

2022-01-16 16:52 UTC, kliiva5 commented
Muutsin draftist -> tavaliseks pull requestiks tagasi (kodeeringu mured veel lahendamisel - teen vast teise PR-i selle jaoks). Ei tea kumma viisi harrastajad olete (kas rebase + force push, või merge dev into feature mahajäänud harude raames), et ei teinud hetke seda liigutust.

2022-01-17 13:39 UTC, mikktarvas approved these changes

2022-01-17 13:42 UTC, mikktarvas commented
@kliiva5 pull request on approved, mis tähendab et on lubatud teostada merge dev harusse. Tõmba dev haru kõigepealt siia harusse ning deploy rakendus demo serverisse. Veendu demo serveris selles, et rakendus toimib nii nagu vaja ning peale seda võid pull requestile tavalise merge teha. Viimase asjana tuleks haru eemaldada. Abi demo serverisse paigaldamisega saab @jaagup käest.

2022-02-04 09:19 UTC, mikktarvas submitted a review, later dismissed

2022-05-06 16:45 UTC, mikktarvas requested changes

2022-05-06 16:45 UTC, mikktarvas commented on clusterfinder/src/main/resources/templates/clusterSearch.ftl
> +          return "<div class='truncated-results'>" +
HTML kokku kleepimine stringidest - kas on XSS vastu kaitstud?

2022-05-15 14:50 UTC, kliiva5 commented on clusterfinder/src/main/resources/templates/clusterSearch.ftl
> +          return "<div class='truncated-results'>" +
Äkki nüüd parem - vaadates Harli kooodist natukene, siis muutsin vastavalt:
* Serveri poolelt tulevad kasutused muudetakse esmalt textNode-iks läbi JS-i `document.createTextNode`-i.
* DataTables-ile peab ikkagi andma stringi kujul asja ette renderamiseks aga eelnevalt mainitud pukt peaks juba XSS ohu eemaldama (kui sain koodi sirvide õigesti aru).

2022-05-15 16:31 UTC, mikktarvas approved these changes

2022-05-22 19:14 UTC, mikktarvas requested changes
Build failing.

2022-05-26 07:23 UTC, merged