Robustne pärimine tähemärkide-sõnade-lausete kaupa valmis
centre-for-educational-technology/evkk pull request #91
Opened 2022-03-31 17:05 UTC by harlikodasma

2022-04-01 16:45 UTC, mikktarvas commented
@harlikodasma tuleks rollbackida, 777 andmine failidele ei ole üldiselt korrektne lahendus. Isegi kui parandab hetkel olukorra, siis viitab pigem mingile muule probleemile, millele tuleks korrektne lahendus leida.

2022-04-02 20:51 UTC, harlikodasma commented
@mikktarvas nüüd peaks revertitud olema need muudatused.

2022-04-17 05:43 UTC, mikktarvas requested changes

2022-04-17 05:43 UTC, mikktarvas commented on conf/local_task-scheduler.env
> +EVKK_TASK_SCHEDULER_TEXT_PROCESSING_ENABLED=true
Peab false jääma.

2022-04-17 05:43 UTC, mikktarvas commented on dal/src/main/resources/ee/tlu/evkk/dal/dao/TextDao.xml
> +                     and cast(p4.result::json->'${loendurHelperid.parameeter}' as TEXT) = '${loendurHelperid.vaartus}'
SQL injection probleem.

2022-04-21 10:10 UTC, harlikodasma commented
Selle PRi parandatud sisu läks koos järgmisega mergemisse, mis sõltus selle olemasolust. https://github.com/centre-for-educational-technology/evkk/pull/93

2022-04-21 10:10 UTC, closed without merging