Päring: korpuste seletused hiirega üle hoverides
centre-for-educational-technology/evkk pull request #92
Opened 2022-04-03 12:37 UTC by harlikodasma

2022-04-06 17:05 UTC, mikktarvas requested changes

2022-04-06 17:05 UTC, mikktarvas commented on .vscode/settings.json
> +{
Tundub et see fail peaks .gitignoretud olema aga on läinud commitiga kaasa.

2022-04-08 17:00 UTC, harlikodasma commented on .vscode/settings.json
> +{
Nüüd korras.

2022-04-08 19:26 UTC, mikktarvas approved these changes

2022-04-21 07:34 UTC, merged