Päring: tehtud valikute tühistamine checkboxide abil & väike code refactor
centre-for-educational-technology/evkk pull request #93
Opened 2022-04-03 22:35 UTC by harlikodasma

2022-04-06 17:14 UTC, mikktarvas requested changes

2022-04-06 17:14 UTC, mikktarvas commented on api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
> +        String[] tavaparameetrid = {"korpus", "tekstityyp", "tekstikeel", "keeletase", "abivahendid", "emakeel", "sugu", "haridus", "aasta", "vanus", "elukoht"};
Siin ilmselt saaks lihtsamaks. Mis on täpsemalt päringu eesmärk? Antakse kaasa parameetrid mille põhjal tekste pärida?

2022-04-06 17:14 UTC, mikktarvas commented on conf/local_task-scheduler.env
> +EVKK_TASK_SCHEDULER_TEXT_PROCESSING_ENABLED=true
Peab false peale jääma.

2022-04-06 17:14 UTC, mikktarvas commented on dal/src/main/resources/ee/tlu/evkk/dal/dao/TextDao.xml
> +                     and cast(p4.result::json->'${loendurHelperid.parameeter}' as TEXT) = '${loendurHelperid.vaartus}'
SQL injection oht.

2022-04-10 11:42 UTC, harlikodasma commented on api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
> +        String[] tavaparameetrid = {"korpus", "tekstityyp", "tekstikeel", "keeletase", "abivahendid", "emakeel", "sugu", "haridus", "aasta", "vanus", "elukoht"};
Päring annab ette array väärtustega, parameetrid on õiges järjekorras Javas defineeritud. Edasi tehakse loendus ja seotakse SQL lausesse. Oli ka eelnevalt samamoodi tehtud, nüüd lihtsalt lisasin parameetereid juurde, mis frontend päringuga kaasa annab.

2022-04-10 12:03 UTC, harlikodasma commented on conf/local_task-scheduler.env
> +EVKK_TASK_SCHEDULER_TEXT_PROCESSING_ENABLED=true
Muudetud

2022-04-10 12:04 UTC, harlikodasma commented on dal/src/main/resources/ee/tlu/evkk/dal/dao/TextDao.xml
> +                     and cast(p4.result::json->'${loendurHelperid.parameeter}' as TEXT) = '${loendurHelperid.vaartus}'
Parandatud

2022-04-10 12:08 UTC, mikktarvas approved these changes

2022-04-21 09:16 UTC, mikktarvas approved these changes

2022-04-21 10:08 UTC, merged